const jobs_illiterate = [
    {type: "agriculture / rural", title: "Farmer", description: "Tilling land, sowing, reaping, and raising animals for a lord or for subsistence."},
    {type: "agriculture / rural", title: "Laborer / Husbandman", description: "Performing general labor on an estate."},
    {type: "agriculture / rural", title: "Shepherd / Animal Herder", description: "Tending to livestock."},
    {type: "agriculture / rural", title: "Miller", description: "Operating a mill to grind grain, a relatively well-off but sometimes 'contemptible' profession."},
    {type: "agriculture / rural", title: "Logger", description: "Felling trees and preparing wood."},
    {type: "agriculture / rural", title: "Hunter / Fisherman", description: "Providing food through hunting or fishing."},
    {type: "Craft / Trade", title: "Blacksmith", description: "Forging tools, weapons, and general ironwork."},
    {type: "Craft / Trade", title: "", description: ""},
    {type: "Craft / Trade", title: "", description: ""},
    {type: "Craft / Trade", title: "", description: ""},
    {type: "Craft / Trade", title: "", description: ""},
    {type: "Craft / Trade", title: "", description: ""},
    {type: "Craft / Trade", title: "", description: ""},
    {type: "Craft / Trade", title: "", description: ""},
    {type: "Craft / Trade", title: "", description: ""},
    {type: "Craft / Trade", title: "", description: ""},
    {type: "Craft / Trade", title: "", description: ""},
    {type: "Craft / Trade", title: "", description: ""},
]